export const CartActionTypes = {
  TOGGLE_CART_DROP_DOWN: "TOGGLE_CART_DROP_DOWN",
  ADD_CART_ITEM: "ADD_CART_ITEM",
  INCREASE_ITEM_QUANTITY: "INCREASE_ITEM_QUANTITY",
  DECREASE_ITEM_QUANTITY: "DECREASE_ITEM_QUANTITY",
  REMOVE_ITEM: "REMOVE_ITEM",
  ADD_ATTRIBUTE_SELECTION_INDEX: "ADD_ATTRIBUTE_SELECTION_INDEX"
};
